### ISSUE TITLE
i have an error when i run the code

### ISSUE THREAD

**Issue by KnightWalker32** [brainbreaker/WITTY#1]
Process: brainbreaker.bargainhawk, PID: 15984
                                                                          com.firebase.client.FirebaseException: Failed to bounce to type
                                                                              at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:185)
                                                                              at brainbreaker.witty.SellerFragments.ProductFragment$1.onDataChange(ProductFragment.java:90)
                                                                              at com.firebase.client.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:53)
                                                                              at com.firebase.client.core.view.DataEvent.fire(DataEvent.java:45)
                                                                              at com.firebase.client.core.view.EventRaiser$1.run(EventRaiser.java:38)
                                                                              at android.os.Handler.handleCallback(Handler.java:751)
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                              at android.os.Looper.loop(Looper.java:154)
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6077)
                                                                              at java.lang.reflect.Method.invoke(Native Method)
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866)
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756)
                                                                           Caused by: com.fasterxml.jackson.databind.JsonMappingException: Numeric value (300341223245) out of range of int
                                                                              at [Source: java.io.StringReader@24638d; line: 1, column: 22] (through reference chain: brainbreaker.witty.Classes.ProductClass["price"])
                                                                              at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1311)
                                                                              at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:297)
                                                                              at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:121)
                                                                              at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:2888)
                                                                              at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2034)
                                                                              at com.firebase.client.DataSnapshot.getValue(DataSnapshot.java:183)
                                                                              at brainbreaker.witty.SellerFragments.ProductFragment$1.onDataChange(ProductFragment.java:90) 
                                                                              at com.firebase.client.core.ValueEventRegistration.fireEvent(ValueEventRegistration.java:53) 
                                                                              at com.firebase.client.core.view.DataEvent.fire(DataEvent.java:45) 
                                                                              at com.firebase.client.core.view.EventRaiser$1.run(EventRaiser.java:38) 
                                                                              at android.os.Handler.handleCallback(Handler.java:751) 
                                                                              at android.os.Handler.dispatchMessage(Handler.java:95) 
                                                                              at android.os.Looper.loop(Looper.java:154) 
                                                                              at android.app.ActivityThread.main(ActivityThread.java:6077) 
                                                                              at java.lang.reflect.Method.invoke(Native Method) 
                                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:866) 
                                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:756) 
                                                                           Caused by: com.fasterxml.jackson.core.JsonParseException: Numeric value (300341223245) out of range of int
                                                                           at [Source: java.io.StringReader@24638d; line: 1, column: 22]
                                                                              at com.fasterxml.jackson.core.JsonParser._constructError(JsonParser.java:1369)
                                                                              at com.fasterxml.jackson.core.base.ParserMinimalBase._reportError(ParserMinimalBase.java:599)
                                                                              at com.fasterxml.jackson.core.base.ParserBase.convertNumberToInt(ParserBase.java:847)
                                                                              at com.fasterxml.jackson.core.base.ParserBase.getIntValue(ParserBase.java:643)
                                                                              at com.fasterxml.jackson.databind.deser.std.StdDeserializer._parseInteger(StdDeserializer.java:306)
                                                                              at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:319)
                                                                              at com.fasterxml.jackson.databind.deser.std.NumberDeserializers$IntegerDeserializer.deserialize(NumberDeserializers.java:301)
                                                                              at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:464)
                                                                              at com.fasterxml.jackson.databind.deser.impl.FieldProperty.deserializeAndSet(FieldProperty.java:107)
                                                                              at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:295)
                                                                              	... 15 more

**Comment by gautamp8** [comment]
Hi @KnightWalker32, Sorry for the delayed response. The firebase SDK used in the code is deprecated. The code is just there for the reference. I'm no longer working on it. 

I'd suggest you read the updated firebase documentation, make your own database of products according to the POJOs in the app/src/main/java/brainbreaker/witty/Classes package. 

For reference, you can take a look at this JSON export of my database: https://github.com/brainbreaker/WITTY/blob/master/bargainkart-export%20(1).json

If you do that correctly and update the relevant firebase code according to their latest documentation you'd be able to run the app. 

Good luck!
